# .github/workflows/security.yml
name: SBOM (Syft only)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.16.0
  
    semgrep:
      runs-on: ubuntu-latest
      container:
        image: semgrep/semgrep

      steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto

       
