# .github/workflows/security.yml
name: SBOM (Syft only)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
    sbom:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.16.0
  
    semgrep:
      runs-on: ubuntu-latest
      container:
        image: semgrep/semgrep
      steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto
      
    gitleaks:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            lfs: true
  
        - name: Install Gitleaks
          run: |
            curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz \
            | tar -xz gitleaks
            sudo mv gitleaks /usr/local/bin/gitleaks
  
        - name: Scan full history
          run: |
            gitleaks detect \
              --source "." \
              --log-opts="--all --full-history" \
              --redact \
              --exit-code 1

